version: '3'
services:
  dev_product:
    build: ./product
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
  dev_inventory:
    build: ./inventory
    command: sh -c "npm run start"
    ports:
      - "3001:3000"
  dev_order:
    build: ./order
    command: sh -c "npm run start"
    ports:
      - "3002:3000"